name: Testing

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing for TypeScript@${{ matrix.typescript-version }}
    timeout-minutes: 5
    
    strategy:
      fail-fast: false
      matrix:
        typescript-version:
          - latest
          - next

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
          cache: npm
      
      - name: Install dependencies
        run: |
          npm ci
          npm i -D typescript@${{ matrix.typescript-version }}
          npm ls
          npm outdated --long || npm update

      - name: Test type-checking
        run: npm test
