name: Testing

permissions:
  contents: read

on:
  push:
  pull_request:

  workflow_dispatch:
    inputs:
      do-update:
        description: Update dependencies
        type: boolean
        default: false
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
          cache: npm
      
      - name: Install dependencies
        run: |
          npm ci
          npm ls
          npm outdated
        
      - name: Update dependencies
        if: inputs.do-update
        continue-on-error: true
        run: npm update

      - name: Test type-checking
        run: npm test